version: "3.1"
services: 
  db:
    image: postgres:14-alpine
    restart: always
    ports: 
      - "5432:5432"
    environment:
      - POSTGRES_DB=cube_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes: 
      - db:/var/lib/postgresql/data
  cube:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    environment:
      - DB_HOST=db
      - DB_NAME=cube_db
      - DB_USER=postgres
      - DB_PASSWORD=password
    ports:
      - "8080:8080"
    depends_on: 
      - db
volumes: 
  db: